# Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. 
In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

<img alt="Image showing ndnumpy and dimensional tensors" src="images/2-tensor-1.png" width="60%"/>

Tensors are similar to `NumPy’s`ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory address, eliminating the need to copy data will a capability called `bridge-to-np-label`. Tensors are also optimized for automatic differentiation (we'll see more about that later in the Autograd unit). If you’re familiar with `ndarrays`, you’ll be right at home with the Tensor API. If not, follow along!

Let's start by setting up our environment.

# Tensors

张量是一种专门的数据结构，与数组和矩阵非常相似。在PyTorch中，我们使用张量来编码一个模型的输入和输出，以及模型的参数。

<img alt="Image showing ndnumpy and dimensional tensors" src="images/2-tensor-1.png" width="60%"/>

张量类似于`NumPy`的ndarrays，只是张量可以在GPU或其他硬件加速器上运行。事实上，张量和NumPy数组通常可以共享相同的底层内存地址，不需要复制数据，这种能力称为 `bridge-to-np-label`。张量也为自动微分进行了优化（我们将在后面的Autograd单元中看到更多的内容）。如果你熟悉 `ndarrays`，你就会对张量API很熟悉。如果不熟悉，那就跟着做吧!

让我们从设置我们的环境开始。

In [ ]:
%matplotlib inline
import torch
import numpy as np

# Initializing a Tensor

Tensors can be initialized in various ways. Take a look at the following examples:

## Directly from data

Tensors can be created directly from data. The data type is automatically inferred.



# 初始化一个张量

张量可以通过不同的方式被初始化。请看下面的例子。

## 直接来自数据

张量可以直接从数据中创建。数据类型是自动推断出来的。

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

## From a NumPy array(来自Numpy数组)

Tensors can be created from NumPy arrays and vice versa.  Since, numpy _'np_array'_ and tensor _'x_np'_ share the same memory location here, changing the value for one will change the other.  


张量可以从NumPy数组中创建，反之亦然。 由于numpy _'np_array'_和tensor _'x_np'_在这里共享同一个内存位置，改变一个的值就会改变另一个。

In [23]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(f"Numpy np_array value: \n {np_array} \n")
print(f"Tensor x_np value: \n {x_np} \n")

np.multiply(np_array, 2, out=np_array)

print(f"Numpy np_array after * 2 operation: \n {np_array} \n")
print(f"Tensor x_np value after modifying numpy array: \n {x_np} \n")

Numpy np_array value: 
 [[1 2]
 [3 4]] 

Tensor x_np value: 
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32) 

Numpy np_array after * 2 operation: 
 [[2 4]
 [6 8]] 

Tensor x_np value after modifying numpy array: 
 tensor([[2, 4],
        [6, 8]], dtype=torch.int32) 



## From another tensor:

The new tensor retains the properties (shape, data type) of the argument tensor, unless explicitly overridden.

新的张量保留了参数张量的属性（形状、数据类型），除非明确重写。


In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2476, 0.2297],
        [0.6623, 0.8990]]) 



## With random or constant values:

``shape`` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.  Shape shows the number of rows and columns in the tensor.  E.g. shape = (# of rows, # of columns).

``shape``是张量维度的元组。在下面的函数中，它决定了输出张量的维度。 形状显示张量中的行和列的数量。 例如，shape = (# of rows, # of columns).



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4424, 0.4927, 0.5646],
        [0.7742, 0.0868, 0.3927]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Attributes of a Tensor

Tensor attributes describe their shape, data type, and the device on which they are stored.

张量属性描述了它们的形状、数据类型以及存储它们的设备。


In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operations on Tensors

There are more than 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing). For sampling and reviewing, you'll find a comprehensive description [here](https://pytorch.org/docs/stable/torch.html).

Each of these operations can be run on the GPU (at typically higher speeds than on a
CPU).
- CPUs have up to 16 cores. Cores are units that do the actual computation. Each core processes tasks in a sequential order (one task at a time).
- GPUs have 1000s of cores.  GPU cores handle computations in parallel processing. Tasks are divided and processed across the different cores. That's what makes GPUs faster than CPUs in most cases. GPUs perform better with large data than small data. GPU are typically used for high-intensive computation of graphics or neural networks (we'll learn more about that later in the Neural Network unit).
- PyTorch can use the Nvidia CUDA library to take advantage of their GPU cards.

<img alt="Diagram showing workload between cpu and gpu" src="images/2-tensor-2.png"/>

By default, tensors are created on the CPU. Tensors can also be computed to GPUs; to do that, you need to move them using the `.to` method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!


有 100 多种张量运算，包括算术、线性代数、矩阵运算（转置、索引、切片）。 对于抽样和审查，您会在[此处](https://pytorch.org/docs/stable/torch.html) 找到全面的描述。

这些操作中的每一个都可以在 GPU 上运行（速度通常比在
中央处理器）。
- CPU 最多有 16 个内核。 核心是进行实际计算的单元。 每个核心按顺序处理任务（一次一个任务）。
- GPU 有 1000 个核心。 GPU 核心处理并行处理中的计算。 任务在不同的核心上进行划分和处理。 这就是 GPU 在大多数情况下比 CPU 更快的原因。 GPU 处理大数据比处理小数据表现更好。 GPU 通常用于图形或神经网络的高强度计算（我们将在稍后的神经网络单元中了解更多相关信息）。
- PyTorch 可以使用 Nvidia CUDA 库来利用他们的 GPU 卡。
默认情况下，张量是在 CPU 上创建的。 张量也可以计算到 GPU； 为此，您需要使用 .to 方法移动它们（在检查 GPU 可用性之后）。 请记住，跨设备复制大型张量在时间和内存方面可能会很昂贵！


In [2]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

Try out some of the operations from the list.
If you're familiar with the NumPy API, you'll find the Tensor API a breeze to use.

尝试列表中的一些操作。如果您熟悉 NumPy API，您会发现使用 Tensor API 轻而易举。

## Standard numpy-like indexing and slicing:

In [9]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## Joining tensors
You can use `torch.cat` to concatenate a sequence of tensors along a given dimension.
`torch.stack` is another tensor joining option that is subtly different from ``torch.cat``.

您可以使用 `torch.cat` 沿给定维度连接一系列张量。
`torch.stack` 是另一个张量连接选项，与 ``torch.cat`` 略有不同。



In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [3]:
import torch
a=torch.randn(3,4) #随机生成一个shape（3，4）的tensort
b=torch.randn(2,4) #随机生成一个shape（2，4）的tensor

print(torch.cat([a,b],dim=0) )
#返回一个shape（5，4）的tensor
#把a和b拼接成一个shape（5，4）的tensor，
#可理解为沿着行增加的方向（即纵向）拼接

a=torch.randn(3,4)
b=torch.randn(3,4)

c=torch.stack([a,b],dim=0)
#返回一个shape(2,3,4)的tensor,新增的维度2分别指向a和b
print(c)
d=torch.stack([a,b],dim=1)
#返回一个shape（3,2,4）的tensor，新增的维度2分别指向相应的a的第i行和b的第i行
d

tensor([[ 2.8340,  1.2816, -0.8016, -0.1380],
        [ 0.4937,  1.6309, -0.3095,  0.0281],
        [-0.3200, -0.7727,  1.9499,  0.4538],
        [-0.2160, -0.5823, -0.3773, -0.6511],
        [ 0.2444, -0.2264, -0.4019, -0.4739]])
tensor([[[-1.2215,  1.4380, -1.2521,  0.1376],
         [ 1.0475,  1.1167,  1.6312,  0.7649],
         [-1.1945, -0.3838,  1.1138, -1.5418]],

        [[-0.0770, -0.3508,  0.4797, -3.2875],
         [-0.7917,  1.3613,  0.4882,  0.3139],
         [ 0.7273,  0.7288,  0.4425, -1.0175]]])


tensor([[[-1.2215,  1.4380, -1.2521,  0.1376],
         [-0.0770, -0.3508,  0.4797, -3.2875]],

        [[ 1.0475,  1.1167,  1.6312,  0.7649],
         [-0.7917,  1.3613,  0.4882,  0.3139]],

        [[-1.1945, -0.3838,  1.1138, -1.5418],
         [ 0.7273,  0.7288,  0.4425, -1.0175]]])

## Arithmetic operations



In [11]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
#这计算两个张量之间的矩阵乘法。 y1、y2、y3 将具有相同的值
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
#这计算逐元素乘积。 z1、z2、z3 将具有相同的值
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

## Single-element tensors
If you have a one-element tensor, for example by aggregating all
values of a tensor into one value, you can convert it to a Python
numerical value using `item()`:

如果你有一个单元素张量，例如通过聚合所有
张量的值转换为一个值，你可以将它转换为 Python
使用 item() 的数值：

In [12]:
agg = tensor.sum()
agg_item = agg.item()  
print(agg_item, type(agg_item))

12.0 <class 'float'>


## In-place operations
Operations that store the result into the operand are called in-place. They are denoted by a ``_`` suffix. 
For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.

> **Note:** In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

将结果存储到操作数中的操作称为就地操作。 它们由 ``_`` 后缀表示。
例如：``x.copy_(y)``、``x.t_()``，将改变``x``。

> **注意：**就地操作可以节省一些内存，但在计算导数时可能会出现问题，因为会立即丢失历史记录。 因此，不鼓励使用它们。



In [13]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change	the other.

CPU上的张量和NumPy数组可以共享它们的底层内存
位置，改变一个就会改变另一个。
### Tensor to NumPy array

In [14]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

张量的变化反映在 NumPy 数组中。


In [15]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to Tensor

In [16]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.

NumPy 数组的变化反映在张量中。


In [17]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
